@startuml battleship_class_diagram

skinparam classAttributeIconSize 0
'left to right direction
hide circle

abstract class View {
    + __init__() {abstract}
    + menu(text, options) {abstract}
    + msg(text) {abstract}
    + get_intput(validator) {abstract}
}

class GameView {
    + __init__()
    + render(grid)
}

class ShipView {
    + __init__()
}

class PlayerView {
    + __init__()
}

abstract class Player {
    - name: str
    - score: int
    - date_of_birth: datetime
    + __init__(name, dob) {abstract}
    + name()
    + name(str)
    + score()
    + date_of_birth()
    + add_score(int)
    + play_move(grid, game_ctrl) {abstract}
    + place_ship(game_ctrl) {abstract}
}

class HumanPlayer {
    + __init__(name, dob)
    + play_move(grid, game_ctrl)
    + place_ship(game_ctrl)
    + coord2idx(coord)
}

class ComputerPlayer {
    + __init__(name, dob)
    + play_move(grid, game_ctrl)
    + place_ship(game_ctrl)
}

Player <|-- HumanPlayer
Player <|-- ComputerPlayer

View <|-- ShipView
View <|-- GameView
View <|-- PlayerView

@enduml