@startuml battleship_class_diagram

skinparam classAttributeIconSize 0
left to right direction
hide circle

class GameControl {
    - players :: Player[]
    - match :: Match
    - ui :: UserInteface
    + __init__()
    + start()
    + add_user(str)
    + del_user(str)
    + view_scores()
}

class Grid {
    - height :: int
    - width :: int
    - ships :: Ship[]
    - shots :: [][]
    + place_ship(ship)
    + check_hit(coord)
    + check_defeat()
}
class Match {
    - player_list :: Player[]
    - ui :: UserInterface
    - players :: (Player, Player) {field} 
    - grids :: (Grid, Grid) {field}
    + __init__(Player[], UserInterface)
    + main_loop()
    + turn()
}
abstract class Player {
    - name :: str
    - score :: int
    + __init__() {abstract}
    + name()
    + name(str)
    + score()
    + add_score(int)
    + play_move() {abstract}
}

class Ship {
    - shape :: bool[][]
    - orientation :: int
    - position :: (int, int) {field}
    - sunk :: bool
    + check_hit(coord)
    + check_sunk()
}

class GameLog {}
class UserInterface {}
class HumanPlayer {}
class ComputerPlayer {}

GameControl <-- GameLog
GameControl <-- UserInterface

Player o-- GameControl

HumanPlayer --|> Player
ComputerPlayer --|> Player

Match --> GameControl
Match <-- Grid

Grid <-- Ship

@enduml